steps:
  # 커스텀 Kaniko 이미지 빌드 스텝
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - build
    - -t
    - us-west1-docker.pkg.dev/swit-ops/test-231019/custom-kaniko-image:latest  # 커스텀 Kaniko 이미지의 경로 및 태그
    - -f
    - ./Dockerfile
    - .

options:
  machineType: 'N1_HIGHCPU_8'
